# cvista Lever B (expanded 2026-06-14): 564 original + 178 ref-closure-safe additions = 742.
# 2026-06-18: +1 (vtkHyperTreeGridGenerateFieldStrategy) = 743. It is the abstract
# base of the GenerateFields strategy family whose concrete subclasses
# (vtkHyperTreeGridCellCenter/CellSize/TotalVisibleVolume/ValidCellStrategy) and the
# vtkHyperTreeGridGenerateFields filter that drives them are ALL already nocompiled,
# leaving this base a pure orphan: zero kept-source includers, zero kept subclasses,
# no ::New()/factory (abstract, vtkObject-derived), not an object-factory override.
# Closure: C++ source ref-scan + transitive ::New() bases. Generated-code refs (the
# per-module vtk*ObjectFactory.cxx override registrations) are NOT in source, so 2
# factory-override classes (vtkPAxisAlignedReflectionFilter, vtkPResampleWithDataSet)
# were restored after the import-smoke surfaced their undefined ::New() at dlopen.
# Validated: pyvista core+plotting suite green at 8 known env-fails, 0 new (9731 passed).
set(CVISTA_NOCOMPILE_CLASSES
  vtk3DCursorRepresentation
  vtk3DCursorWidget
  vtkAbstractGridConnectivity
  vtkAbstractInteractionDevice
  vtkAbstractPolygonalHandleRepresentation3D
  vtkAbstractRenderDevice
  vtkAbstractSplineRepresentation
  vtkAdaptiveResampleToImage
  vtkAdaptiveTemporalInterpolator
  vtkAdjacencyMatrixToEdgeTable
  vtkAffineRepresentation
  vtkAffineRepresentation2D
  vtkAffineWidget
  vtkAggregateDataSetFilter
  vtkAggregateToPartitionedDataSetCollection
  vtkAlignImageDataSetFilter
  vtkAmoebaMinimizer
  vtkAngleRepresentation
  vtkAngleRepresentation2D
  vtkAngleRepresentation3D
  vtkAngleWidget
  vtkAngularPeriodicFilter
  vtkAnimateModes
  vtkAnnulus
  vtkAppendLocationAttributes
  vtkArchiver
  vtkArcPlotter
  vtkAreaContourSpectrumFilter
  vtkArrayCalculator
  vtkArrayDataAlgorithm
  vtkArrayDataReader
  vtkArrayDataWriter
  vtkArrayExtentsList
  vtkArrayNorm
  vtkArrayReader
  vtkArrayRename
  vtkArrayRenderer
  vtkArrayToTable
  vtkArrayWeights
  vtkArrayWriter
  vtkAssignAttribute
  vtkAttributesErrorMetric
  vtkAvatar
  vtkAxesTransformRepresentation
  vtkAxesTransformWidget
  vtkAxisAlignedTransformFilter
  vtkBackgroundColorMonitor
  vtkBiDimensionalRepresentation
  vtkBiDimensionalRepresentation2D
  vtkBiDimensionalWidget
  vtkBilinearQuadIntersection
  vtkBinCellDataFilter
  vtkBiomTableReader
  vtkBivariateLinearTableThreshold
  vtkBlankStructuredGrid
  vtkBlankStructuredGridWithImage
  vtkBlockIdScalars
  vtkBooleanTexture
  vtkBreakPoint
  vtkBrokenLineWidget
  vtkBrownianPoints
  vtkBYUWriter
  vtkCachedStreamingDemandDrivenPipeline
  vtkCameraNode
  vtkCameraPathRepresentation
  vtkCameraPathWidget
  vtkCameraRepresentation
  vtkCameraWidget
  vtkCastToConcrete
  vtkCategoryLegend
  vtkCellGridElevation
  vtkCellGridPointProbe
  vtkCellGridRenderRequest
  vtkCellGridSampleQuery
  vtkCenteredSliderRepresentation
  vtkCenteredSliderWidget
  vtkCGNSFileSeriesReader
  vtkChacoGraphReader
  vtkChacoReader
  vtkChartHistogram2D
  vtkChartMatrix
  vtkChartParallelCoordinates
  vtkCleanUnstructuredGridCells
  vtkClearZPass
  vtkClosedSurfacePointPlacer
  vtkCMLMoleculeReader
  vtkCollapseGraph
  vtkCollapseVerticesByArray
  vtkCollectGraph
  vtkCollectPolyData
  vtkCollectTable
  vtkColorLegend
  vtkColorTransferControlPointsItem
  vtkColorTransferFunctionItem
  vtkCompassRepresentation
  vtkCompassWidget
  vtkCompositeCellGridMapper
  vtkCompositeCellGridReader
  vtkCompositeControlPointsItem
  vtkCompositeCutter
  vtkCompositeDataDisplayAttributesLegacy
  vtkCompositeTransferFunctionItem
  vtkCone
  vtkConnectedPointsFilter
  vtkContextArea
  vtkContextView
  vtkContinuousScatterplot
  vtkContinuousValueWidget
  vtkContinuousValueWidgetRepresentation
  vtkControlPointsItem
  vtkCONVERGECFDCGNSReader
  vtkConvertToPolyhedra
  vtkConvexHull2D
  vtkCoordinateFrame
  vtkCoordinateFrameRepresentation
  vtkCoordinateFrameWidget
  vtkCountFaces
  vtkCountVertices
  vtkCPExodusIIElementBlock
  vtkCPExodusIIInSituReader
  vtkCriticalTime
  vtkCurveRepresentation
  vtkCutMaterial
  vtkCylindricalTransform
  vtkDataArrayCollectionIterator
  vtkDataObjectGenerator
  vtkDataObjectReader
  vtkDataObjectWriter
  vtkDataSetGradient
  vtkDataSetGradientPrecompute
  vtkDataSetRegionSurfaceFilter
  vtkDataSetToDataObjectFilter
  vtkDataTransferHelper
  vtkDateToNumeric
  vtkDecimatePolylineCustomFieldStrategy
  vtkDeflectNormals
  vtkDeformPointSet
  vtkDelimitedTextWriter
  vtkDensifyPointCloudFilter
  vtkDepthSortPolyData
  vtkDiagonalMatrixSource
  vtkDicer
  vtkDijkstraImageContourLineInterpolator
  vtkDijkstraImageGeodesicPath
  vtkDIMACSGraphReader
  vtkDIMACSGraphWriter
  vtkDirectedGraphAlgorithm
  vtkDiscretizableColorTransferFunction
  vtkDistanceToCamera
  vtkDotProductSimilarity
  vtkDSPFilterDefinition
  vtkDSPFilterGroup
  vtkDuplicatePolyData
  vtkDynamic2DLabelMapper
  vtkEarthSource
  vtkEdgeCenters
  vtkEdgePoints
  vtkEllipsoidTensorProbeRepresentation
  vtkEmptyRepresentation
  vtkEndFor
  vtkEnsembleSource
  vtkEnSightGoldCombinedReader
  vtkEnSightMasterServerReader
  vtkEnSightSOSGoldReader
  vtkEnSightWriter
  vtkEqualizerContextItem
  vtkEqualizerFilter
  vtkEquirectangularToCubeMapTexture
  vtkEuclideanClusterExtraction
  vtkExecutableRunner
  vtkExecutionAggregator
  vtkExecutionRange
  vtkExecutionTimer
  vtkExodusIIWriter
  vtkExpandSelectedGraph
  vtkExplicitStructuredGridCrop
  vtkExplicitStructuredGridSurfaceFilter
  vtkExprTkFunctionParser
  vtkExtentRCBPartitioner
  vtkExtractArray
  vtkExtractBlockUsingDataAssembly
  vtkExtractCellsAlongPolyLine
  vtkExtractCTHPart
  vtkExtractDataOverTime
  vtkExtractDataSets
  vtkExtractFunctionalBagPlot
  vtkExtractGhostCells
  vtkExtractHierarchicalBins
  vtkExtractHistogram
  vtkExtractLevel
  vtkExtractParticlesOverTime
  vtkExtractPointCloudPiece
  vtkExtractPolyDataPiece
  vtkExtractSelectedArraysOverTime
  vtkExtractSelectedRows
  vtkExtractSelectedTree
  vtkExtractStatisticalModelTables
  vtkExtractSubsetWithSeed
  vtkExtractSurface
  vtkExtractTensorComponents
  vtkExtractTimeSteps
  vtkExtractUnstructuredGridPiece
  vtkExtractUserDefinedPiece
  vtkExtractVectorComponents
  vtkFacetWriter
  vtkFastLabeledDataMapper
  vtkFastSplatter
  vtkFieldDataSerializer
  vtkFieldDataToDataSetAttribute
  vtkFiniteElementFieldDistributor
  vtkFinitePlaneRepresentation
  vtkFinitePlaneWidget
  vtkFitToHeightMapFilter
  vtkFixedSizeHandleRepresentation3D
  vtkFlagpoleLabel
  vtkFloatingPointExceptions
  vtkFocalPlaneContourRepresentation
  vtkForceStaticMesh
  vtkForceTime
  vtkForEach
  vtkFreeTypeStringToImage
  vtkFrustum
  vtkFunctionParser
  vtkGaussianCubeReader2
  vtkGenerateIndexArray
  vtkGenerateTimeSteps
  vtkGenericEdgeTable
  vtkGenericImageInterpolator
  vtkGenericVertexAttributeMapping
  vtkGeometricErrorMetric
  vtkGlobFileNames
  vtkGLSLModPixelDebugger
  vtkGLTFWriter
  vtkGoldenBallSource
  vtkGraphAnnotationLayersFilter
  vtkGraphHierarchicalBundleEdges
  vtkGraphLayoutFilter
  vtkGraphMapper
  vtkGraphToGlyphs
  vtkGraphToPoints
  vtkGraphToPolyData
  vtkGraphWeightEuclideanDistanceFilter
  vtkGraphWeightFilter
  vtkGroupLeafVertices
  vtkGroupTimeStepsFilter
  vtkHausdorffDistancePointSetFilter
  vtkHierarchicalBinningFilter
  vtkHierarchicalBoxDataSetAlgorithm
  vtkHierarchicalDataExtractDataSets
  vtkHierarchicalDataExtractLevel
  vtkHierarchicalDataLevelFilter
  vtkHierarchicalDataSetGeometryFilter
  vtkHierarchicalPolyDataMapper
  vtkHull
  vtkHyperTreeGridAxisClip
  vtkHyperTreeGridAxisCut
  vtkHyperTreeGridAxisReflection
  vtkHyperTreeGridCellCenters
  vtkHyperTreeGridCellCenterStrategy
  vtkHyperTreeGridCellSizeStrategy
  vtkHyperTreeGridDepthLimiter
  vtkHyperTreeGridEvaluateCoarse
  vtkHyperTreeGridExtractGhostCells
  vtkHyperTreeGridFeatureEdges
  vtkHyperTreeGridGenerateFields
  vtkHyperTreeGridGenerateFieldStrategy
  vtkHyperTreeGridGenerateGlobalIds
  vtkHyperTreeGridGenerateProcessIds
  vtkHyperTreeGridGradient
  vtkHyperTreeGridOutlineFilter
  vtkHyperTreeGridPreConfiguredSource
  vtkHyperTreeGridRemoveGhostCells
  vtkHyperTreeGridSource
  vtkHyperTreeGridThreshold
  vtkHyperTreeGridToDualGrid
  vtkHyperTreeGridTotalVisibleVolumeStrategy
  vtkHyperTreeGridValidCellStrategy
  vtkHyperTreeGridVisibleLeavesSize
  vtkIconGlyphFilter
  vtkImageAnisotropicDiffusion2D
  vtkImageAnisotropicDiffusion3D
  vtkImageCacheFilter
  vtkImageCityBlockDistance
  vtkImageConnector
  vtkImageConvolve
  vtkImageCorrelation
  vtkImageCroppingRegionsWidget
  vtkImageCursor3D
  vtkImageDataStreamer
  vtkImageDataToExplicitStructuredGrid
  vtkImageDataToHyperTreeGrid
  vtkImageDataToUniformGrid
  vtkImageDivergence
  vtkImageDotProduct
  vtkImageEuclideanDistance
  vtkImageEuclideanToPolar
  vtkImageFourierCenter
  vtkImageGradient
  vtkImageGradientMagnitude
  vtkImageHSIToRGB
  vtkImageHSVToRGB
  vtkImageHybridMedian2D
  vtkImageIdealHighPass
  vtkImageIdealLowPass
  vtkImageInPlaceFilter
  vtkImageIslandRemoval2D
  vtkImageLaplacian
  vtkImageLogarithmicScale
  vtkImageLogic
  vtkImageLuminance
  vtkImageMagnify
  vtkImageMapToRGBA
  vtkImageMask
  vtkImageMaskBits
  vtkImageMathematics
  vtkImageNonMaximumSuppression
  vtkImageNormalize
  vtkImageOpenClose3D
  vtkImageOrthoPlanes
  vtkImageProbeFilter
  vtkImageQuantizeRGBToIndex
  vtkImageRange3D
  vtkImageRGBToHSI
  vtkImageRGBToHSV
  vtkImageRGBToXYZ
  vtkImageRGBToYIQ
  vtkImageSeedConnectivity
  vtkImageSeparableConvolution
  vtkImageSkeleton2D
  vtkImageSlab
  vtkImageSobel2D
  vtkImageSobel3D
  vtkImageSSIM
  vtkImageStencilToImage
  vtkImageThresholdConnectivity
  vtkImageToImageStencil
  vtkImageToPolyDataFilter
  vtkImageToStructuredPoints
  vtkImageTracerWidget
  vtkImageTranslateExtent
  vtkImageVariance3D
  vtkImageWeightedSum
  vtkImageXYZToLAB
  vtkImageYIQToRGB
  vtkImplicitAnnulusRepresentation
  vtkImplicitAnnulusWidget
  vtkImplicitConeRepresentation
  vtkImplicitConeWidget
  vtkImplicitFrustumRepresentation
  vtkImplicitFrustumWidget
  vtkImplicitFunctionToImageStencil
  vtkImplicitHalo
  vtkImplicitProjectOnPlaneDistance
  vtkImplicitTextureCoords
  vtkInformationDataObjectMetaDataKey
  vtkIntegrationGaussianStrategy
  vtkInteractiveArea
  vtkInteractorStyle3D
  vtkInteractorStyleDrawPolygon
  vtkInteractorStyleRubberBand3D
  vtkInteractorStyleUnicam
  vtkInteractorStyleUser
  vtkInterpolateDataSetAttributes
  vtkInvoker
  vtkISIReader
  vtkIVExporter
  # vtkJavaScriptDataWriter: restored to compilation -- VTK::WebGLExporter
  # (pulled in by the restored VTK::WebCore module) references its ::New() and
  # ::SetOutputStream(). It stays in _nowrap_classes (no Python binding needed;
  # used only from C++ inside WebGLExporter), so only the C++ object is added
  # back to the IOCore kit, resolving the dlopen-time undefined symbol.
  vtkJoinTables
  vtkJSONDataSetWriter
  vtkJSONImageWriter
  vtkJSONRenderWindowExporter
  vtkJSONSceneExporter
  vtkKCoreDecomposition
  vtkKdTreePointLocator
  vtkKMeansDistanceFunctorCalculator
  vtkLabeledContourPolyDataItem
  vtkLabeledTreeMapDataMapper
  vtkLabelPlacer
  vtkLabelSizeCalculator
  vtkLagrangianBasicIntegrationModel
  vtkLagrangianMatidaIntegrationModel
  vtkLagrangianParticle
  vtkLagrangianParticleTracker
  vtkLassoStencilSource
  vtkLeaderActor2D
  vtkLevelIdScalars
  vtkLightNode
  vtkLightRepresentation
  vtkLightWidget
  vtkLinearCellExtrusionFilter
  vtkLinearContourLineInterpolator
  vtkLineRepresentation
  vtkLineWidget2
  vtkLinkEdgels
  vtkLissajousPointCloud
  vtkLookupTableItem
  vtkLookupTableWithEnabling
  vtkLoopBooleanPolyDataFilter
  vtkMagnifierRepresentation
  vtkMagnifierWidget
  vtkMapArrayValues
  vtkMapperCollection
  vtkMarkerUtilities
  vtkMaskFields
  vtkMaskPointsFilter
  vtkMaskPolyData
  vtkMatricizeArray
  vtkMeasurementCubeHandleRepresentation3D
  vtkMergeArrays
  vtkMergeCells
  vtkMergeColumns
  vtkMergeDataObjectFilter
  vtkMergeFields
  vtkMergeGraphs
  vtkMergeTables
  vtkMergeTimeFilter
  vtkMergeVectorComponents
  vtkMNIObjectReader
  vtkMNIObjectWriter
  vtkMNITagPointReader
  vtkMNITagPointWriter
  vtkMNITransformReader
  vtkMNITransformWriter
  vtkModelMetadata
  vtkMoleculeToAtomBallFilter
  vtkMoleculeToBondStickFilter
  vtkMoleculeToLinesFilter
  vtkMoleculeToPolyDataFilter
  vtkMRCReader
  vtkMultiBlockMergeFilter
  vtkMultiBlockUnstructuredGridVolumeMapper
  vtkMultiLineRepresentation
  vtkMultiLineWidget
  vtkMultiNewickTreeReader
  vtkMultiTimeStepAlgorithm
  vtkMutableGraphHelper
  vtkNetworkHierarchy
  vtkNewickTreeReader
  vtkNewickTreeWriter
  vtkNonOverlappingAMRAlgorithm
  vtkNormalizeMatrixVectors
  vtkOBBDicer
  vtkOMETIFFReader
  vtkOOGLExporter
  vtkOpenGLES30PolyDataMapper2D
  vtkOpenGLFluidMapper
  vtkOpenGLImageAlgorithmHelper
  vtkOpenGLSphereMapper
  vtkOpenGLStickMapper
  vtkOpenGLSurfaceProbeVolumeMapper
  vtkOrientationRepresentation
  vtkOrientationWidget
  vtkOrientedGlyphFocalPlaneContourRepresentation
  vtkOrientedPolygonalHandleRepresentation3D
  vtkOutlineGlowPass
  vtkOverlappingAMRAlgorithm
  vtkOverlappingAMRLevelIdScalars
  vtkOverlappingCellsDetector
  vtkPanoramicProjectionPass
  vtkParallelCoordinatesInteractorStyle
  vtkParallelopipedRepresentation
  vtkParallelopipedWidget
  vtkParallelVectors
  vtkPartitionBalancer
  vtkPartitionedDataSetAlgorithm
  vtkPartitionedDataSetCollectionSource
  vtkPartitionedDataSetSource
  vtkPassArrays
  vtkPassSelectedArrays
  vtkPassThrough
  vtkPCAAnalysisFilter
  vtkPCACurvatureEstimation
  vtkPCANormalEstimation
  vtkPCAStatistics
  vtkPChacoReader
  vtkPDataSetWriter
  vtkPDirectory
  vtkPeriodicFilter
  vtkPExecutableRunner
  vtkPExtractSelectedArraysOverTime
  vtkPhyloXMLTreeReader
  vtkPhyloXMLTreeWriter
  vtkPHyperTreeGridProbeFilter
  vtkPieceRequestFilter
  vtkPieceScalars
  vtkPiecewiseControlPointsItem
  vtkPiecewiseFunctionAlgorithm
  vtkPiecewiseFunctionItem
  vtkPiecewiseFunctionShiftScale
  vtkPiecewisePointHandleItem
  vtkPImageWriter
  vtkPipelineGraphSource
  vtkPipelineSize
  vtkPixelExtentIO
  vtkPlaybackRepresentation
  vtkPlaybackWidget
  vtkPLinearExtrusionFilter
  vtkPlotBarRangeHandlesItem
  vtkPlotHistogram2D
  vtkPlotParallelCoordinates
  vtkPlotRangeHandlesItem
  vtkPMergeArrays
  vtkPointCloudRepresentation
  vtkPointCloudWidget
  vtkPointConnectivityFilter
  vtkPointDensityFilter
  vtkPointFillPass
  vtkPointOccupancyFilter
  vtkPointSetToMoleculeFilter
  vtkPointsMatchingTransformFilter
  vtkPoissonDiskSampler
  vtkPolarAxesActor
  vtkPolarAxesActor2D
  vtkPolyDataEdgeConnectivityFilter
  vtkPolyDataItem
  vtkPolyDataMapperNode
  vtkPolyDataPointSampler
  vtkPolyDataStreamer
  vtkPolyDataToReebGraphFilter
  vtkPolygonalHandleRepresentation3D
  vtkPolyLineRepresentation
  vtkPolyLineSource
  vtkPolyLineWidget
  vtkPolynomialSolversUnivariate
  vtkPolyPointSource
  vtkPostScriptWriter
  vtkPOutlineCornerFilter
  vtkPOutlineFilter
  vtkPOutlineFilterInternals
  vtkPOVExporter
  vtkPPolyDataNormals
  vtkPProbeFilter
  vtkPProjectSphereFilter
  vtkPReflectionFilter
  vtkPResampleFilter
  vtkProbeLineFilter
  vtkProbePolyhedron
  vtkProbeSelectedLocations
  vtkProgrammableDataObjectSource
  vtkProgrammableElectronicData
  vtkProgrammableSource
  vtkProgressBarRepresentation
  vtkProgressBarWidget
  vtkProjectedTexture
  vtkProjectPointsToPlane
  vtkProjectSphereFilter
  vtkPruneTreeFilter
  vtkPSphereSource
  vtkPSystemTools
  vtkPTextureMapToSphere
  vtkPYoungsMaterialInterface
  vtkQuadraturePointInterpolator
  vtkQuadraturePointsGenerator
  vtkQuadratureSchemeDictionaryGenerator
  vtkQuadRotationalExtrusionFilter
  vtkRadialGridActor2D
  vtkRandomAttributeGenerator
  vtkRandomGraphSource
  vtkRandomHyperTreeGridSource
  vtkRangeHandlesItem
  vtkRearrangeFields
  vtkRecoverGeometryWireframe
  vtkRectilinearGridClip
  vtkRectilinearGridPartitioner
  vtkRecursiveDividingCubes
  vtkReduceTable
  vtkReferenceCount
  vtkReflectionFilter
  vtkRemoveDuplicatePolys
  vtkRemoveGhosts
  vtkRemoveHiddenData
  vtkRemoveIsolatedVertices
  vtkRemoveUnusedPoints
  vtkRenderViewBase
  vtkRenderWidget
  vtkRenderWindowInteractor3D
  vtkResizingWindowToImageFilter
  vtkResourceFileLocator
  vtkRIBExporter
  vtkRIBLight
  vtkRIBProperty
  vtkRISReader
  vtkROIStencilSource
  vtkRotationFilter
  vtkRTXMLPolyDataReader
  vtkSampleImplicitFunctionFilter
  vtkScalarsToColorsItem
  vtkScalarsToTextureFilter
  vtkScatterPlotMatrix
  vtkSectorSource
  vtkSelectionSource
  vtkSEPReader
  vtkSignedDistance
  vtkSimpleBondPerceiver
  vtkSimpleCellTessellator
  vtkSimpleMotionBlurPass
  vtkSingleVTPExporter
  vtkSmoothErrorMetric
  vtkSortFieldData
  vtkSortFileNames
  vtkSparseArrayToTable
  vtkSpatialRepresentationFilter
  vtkSpatioTemporalHarmonicsAttribute
  vtkSpatioTemporalHarmonicsSource
  vtkSPHCubicKernel
  vtkSphereHandleRepresentation
  vtkSpherePuzzle
  vtkSpherePuzzleArrows
  vtkSphereRepresentation
  vtkSphereWidget2
  vtkSphericalPointIterator
  vtkSphericalTransform
  vtkSPHQuarticKernel
  vtkSplineRepresentation
  vtkSplineWidget2
  vtkSplitField
  vtkStitchImageDataWithGhosts
  vtkStrahlerMetric
  vtkStreamerBase
  vtkStreamGraph
  vtkStreamingStatistics
  vtkStringToCategory
  vtkStringToImage
  vtkStringToNumeric
  vtkStructuredAMRGridConnectivity
  vtkStructuredAMRNeighbor
  vtkStructuredGridClip
  vtkStructuredGridConnectivity
  vtkStructuredGridPartitioner
  vtkStructuredNeighbor
  vtkStructuredPointsGeometryFilter
  vtkSubPixelPositionEdgels
  vtkSuperquadric
  vtkSVGContextDevice2D
  vtkSVGExporter
  vtkSynchronizeTimeFilter
  vtkTableToArray
  vtkTableToGraph
  vtkTableToSparseArray
  vtkTableToStructuredGrid
  vtkTableToTreeFilter
  vtkTemporalArrayOperatorFilter
  vtkTemporalDataSetCache
  vtkTemporalDelimitedTextReader
  vtkTemporalFractal
  vtkTemporalInterpolator
  vtkTemporalPathLineFilter
  vtkTemporalShiftScale
  vtkTemporalSmoothing
  vtkTemporalSnapToTimeStep
  vtkTemporalStatistics
  vtkTensorProbeRepresentation
  vtkTensorProbeWidget
  vtkTextRendererStringToImage
  vtkThreadedCallbackQueue
  vtkThreadedCompositeDataPipeline
  vtkThresholdGraph
  vtkThresholdScalars
  vtkThresholdTable
  vtkTimePointUtility
  vtkTimeRange
  vtkTimeSourceExample
  vtkToAffineArrayStrategy
  vtkToImplicitRamerDouglasPeuckerStrategy
  vtkToneMappingPass
  vtkTransferAttributes
  vtkTransformInterpolator
  vtkTransmitPolyDataPiece
  vtkTransmitRectilinearGridPiece
  vtkTransmitStructuredDataPiece
  vtkTransmitStructuredGridPiece
  vtkTransmitUnstructuredGridPiece
  vtkTransposeMatrix
  vtkTransposeTable
  vtkTreeAlgorithm
  vtkTreeBFSIterator
  vtkTreeDFSIterator
  vtkTreeDifferenceFilter
  vtkTreeFieldAggregator
  vtkTreeIterator
  vtkTreeLevelsFilter
  vtkTriangularTCoords
  vtkTriangularTexture
  vtkTrivialConsumer
  vtkTulipReader
  vtkUncertaintyTubeFilter
  vtkUndirectedGraphAlgorithm
  vtkUniformGridAMRAlgorithm
  vtkUniformGridAMRDataIterator
  vtkUniformGridPartitioner
  vtkUniformHyperTreeGridSource
  vtkUnsignedDistance
  vtkUnstructuredGridQuadricDecimation
  vtkUnstructuredGridVolumeZSweepMapper
  vtkValuePass
  vtkVASPAnimationReader
  vtkVASPTessellationReader
  vtkVectorDot
  vtkVectorFieldTopology
  vtkVectorNorm
  vtkVertexDegree
  vtkViewDependentErrorMetric
  vtkVolumeContourSpectrumFilter
  vtkVolumeMapperNode
  vtkVolumeNode
  vtkVolumeOfRevolutionFilter
  vtkVortexCore
  vtkVoxelContoursToSurfaceFilter
  vtkVoxelGrid
  vtkVoxelModeller
  vtkWarpLens
  vtkWarpTo
  vtkWendlandQuinticKernel
  vtkWidgetSet
  vtkWindBladeReader
  vtkWordCloud
  vtkX3D
  vtkX3DExporter
  vtkX3DExporterFIWriter
  vtkX3DExporterWriter
  vtkX3DExporterXMLWriter
  vtkXGMLReader
  vtkXMLFileOutputWindow
  vtkXMLHierarchicalBoxDataFileConverter
  vtkXMLHierarchicalBoxDataReader
  vtkXMLHierarchicalBoxDataWriter
  vtkXMLHierarchicalDataReader
  vtkXMLMultiGroupDataReader
  vtkXMLPartitionedDataSetCollectionReader
  vtkXMLPartitionedDataSetCollectionWriter
  vtkXMLPDataSetWriter
  vtkXMLPHierarchicalBoxDataWriter
  vtkXMLPHyperTreeGridReader
  vtkXMLPHyperTreeGridWriter
  vtkXMLPMultiBlockDataWriter
  vtkXMLPTableReader
  vtkXMLPTableWriter
  vtkXMLPUniformGridAMRWriter
  vtkXMLTreeReader
  vtkXMLUniformGridAMRWriter
  vtkXYZMolReader
  vtkXYZMolReader2
  vtkYoungsMaterialInterface
  CACHE INTERNAL "cvista: classes dropped from the C++ build (pyvista-unused orphans)")
